### ISSUE TITLE
如何重置已有的数据

### ISSUE THREAD

**Issue by miaoxiaozhao** [x1ao4/edition-manager-for-plex#4]
调整了order的内容，重启emp-all，但是好像没有发生变化，请问如何处理？

我是pass用户

**Comment by x1ao4** [comment]
容器 `emp-reset` 是用来运行 `为所有电影重置版本信息` 任务的，它会在启动后运行一次 `为所有电影重置版本信息` 任务，对设置范围内的所有电影进行处理（重置/移除版本信息），并在终端或日志内显示资料库的信息和处理结果，处理完毕后会停止运行。你可以随时启动它来运行 `为所有电影重置版本信息` 任务，它将在每次处理完毕后停止运行。

使用命令 `python3 edition-manager-for-plex.py --reset` 可运行 `为所有电影重置版本信息` 任务，脚本将对设置范围内的所有电影进行处理（重置/移除版本信息），并在控制台显示资料库的信息和处理结果，处理完毕后会结束运行。

请查阅使用说明，重置版本信息后，就可以重新写入新的版本信息了。

**Comment by miaoxiaozhao** [comment]
好的，已经成功了，感谢细致回答。
